train:
  test_size: 0.2
  random_state: 42

experiment:
  name: "01"

experiments:
  exp_01:
    n_estimators: 10
    max_depth: 3
    test_size: 0.2
    random_state: 42

  exp_02:
    n_estimators: 50
    max_depth: 5
    test_size: 0.2
    random_state: 42

  exp_03:
    n_estimators: 100
    max_depth: 1
    test_size: 0.3
    random_state: 42
